import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from 'sonner';
import Navbar from "../../components/Navbar";
import { automaticCleanup } from '@/lib/utils';

// Run automatic cleanup when app starts (only in production to avoid slowing down development)
if (process.env.NODE_ENV === 'production') {
  // Run cleanup asynchronously without blocking the app startup
  automaticCleanup().catch(console.error);
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // You could add automatic cleanup here on app startup
  // import { updateItemRentalStatus } from '@/lib/utils';
  // 
  // // Run cleanup when app starts (only in production)
  // if (process.env.NODE_ENV === 'production') {
  //   updateItemRentalStatus().catch(console.error);
  // }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
         <Navbar />
          <main className="p-6">{children}</main>
          <Toaster position="top-center" richColors closeButton />
        </Providers>
      </body>
    </html>
  );
}
